language: generaic
sudo: required
services:
  - docker

before_install:
  - docker build -t coolasshonky/docker-react-test -f Dockerfile.dev .

script:
  # - docker run coolasshonky/docker-react-test npm run test -- --coverage
  - docker run -e CI=true coolasshonky/docker-react-test npm run test